const menu = {
    list() {
        return [
  {
      "backMenu":[
          {
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "修改",
                          "删除"
                      ],
                      "menu":"管理员管理",
                      "menuJump":"列表",
                      "tableName":"users"
                  }
              ],
              "menu":"管理员管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "删除",
                          "修改"
                      ],
                      "menu":"公共服务类型管理",
                      "menuJump":"列表",
                      "tableName":"dictionaryGonggongfuwu"
                  }
                  ,
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "删除",
                          "修改"
                      ],
                      "menu":"活动类型管理",
                      "menuJump":"列表",
                      "tableName":"dictionaryHuodong"
                  }
                  ,
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "删除",
                          "修改"
                      ],
                      "menu":"社区政务类型管理",
                      "menuJump":"列表",
                      "tableName":"dictionaryNews"
                  }
              ],
              "menu":"基础数据管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "修改",
                          "删除"
                      ],
                      "menu":"论坛管理",
                      "menuJump":"列表",
                      "tableName":"forum"
                  }
              ],
              "menu":"论坛管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "修改",
                          "删除"
                      ],
                      "menu":"公共服务管理",
                      "menuJump":"列表",
                      "tableName":"gonggongfuwu"
                  }
              ],
              "menu":"公共服务管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "修改",
                          "报表",
                          "删除"
                      ],
                      "menu":"社区活动管理",
                      "menuJump":"列表",
                      "tableName":"huodong"
                  }
              ],
              "menu":"社区活动管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "删除"
                      ],
                      "menu":"活动报名管理",
                      "menuJump":"列表",
                      "tableName":"huodongbaoming"
                  }
              ],
              "menu":"活动报名管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "修改",
                          "删除"
                      ],
                      "menu":"社区政务管理",
                      "menuJump":"列表",
                      "tableName":"news"
                  }
              ],
              "menu":"社区政务管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "修改",
                          "删除"
                      ],
                      "menu":"用户管理",
                      "menuJump":"列表",
                      "tableName":"yonghu"
                  }
              ],
              "menu":"用户管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "新增",
                          "修改",
                          "删除"
                      ],
                      "menu":"轮播图管理",
                      "menuJump":"列表",
                      "tableName":"config"
                  }
              ],
              "menu":"轮播图信息"
          }
      ],
      "frontMenu":[],
      "hasBackLogin":"是",
      "hasBackRegister":"否",
      "hasFrontLogin":"否",
      "hasFrontRegister":"否",
      "roleName":"管理员",
      "tableName":"users"
  },
  {
      "backMenu":[
          {
              "child":[
                  {
                      "buttons":[
                          "查看"
                      ],
                      "menu":"论坛管理",
                      "menuJump":"列表",
                      "tableName":"forum"
                  }
              ],
              "menu":"论坛管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看"
                      ],
                      "menu":"公共服务管理",
                      "menuJump":"列表",
                      "tableName":"gonggongfuwu"
                  }
              ],
              "menu":"公共服务管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看"
                      ],
                      "menu":"社区活动管理",
                      "menuJump":"列表",
                      "tableName":"huodong"
                  }
              ],
              "menu":"社区活动管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看",
                          "删除"
                      ],
                      "menu":"活动报名管理",
                      "menuJump":"列表",
                      "tableName":"huodongbaoming"
                  }
              ],
              "menu":"活动报名管理"
          }
          ,{
              "child":[
                  {
                      "buttons":[
                          "查看"
                      ],
                      "menu":"社区政务管理",
                      "menuJump":"列表",
                      "tableName":"news"
                  }
              ],
              "menu":"社区政务管理"
          }
      ],
      "frontMenu":[],
      "hasBackLogin":"是",
      "hasBackRegister":"否",
      "hasFrontLogin":"否",
      "hasFrontRegister":"否",
      "roleName":"用户",
      "tableName":"yonghu"
  }
]
    }
}
export default menu;
